### ISSUE TITLE
Add asset path URL feature

### ISSUE THREAD

**Issue by vietartisans** [vietartisans/templater#10]
* Add asset path URL when we using gulp. it is currently on our repo `light-gulp-composer`

**Comment by buiquangduc** [comment]
cai nay chi la install package kia vao trong templater thoi dung khong? @sondoha

**Comment by sondoha** [comment]
Khong phai, copy code phan asset URL tu ben kia qua repo nay, sau do de minh remove cai repo kia di @buiquangduc
