### ISSUE TITLE
Make a custom function for templater with Twig

### ISSUE THREAD

**Issue by duyngha** [vietartisans/templater#15]
As we discussed in #14. But it still pretty hard to use when we want to make a custom function for Twig template. So my idea is create something like this:
```php
$templater = new \VA\Templater($this->master->path . '/templates');
$templater->addFunction('foo', function (param_1, param_2...) {
// do something awesome here
})
```

What do you guys think?

**Comment by sondoha** [comment]
Done roi nhe Duy @duyngha
