### ISSUE TITLE
Disable display HTML tags in Twig Template

### ISSUE THREAD

**Issue by duyngha** [vietartisans/templater#16]
The templater is showing both HTML tags into the template file which uses Twig

**Comment by sondoha** [comment]
Can you please show me a screenshot? @duyngha

**Comment by duyngha** [comment]
Cai nay ok roi anh. Do a Tri dat HTML dang unicode `&lt;em&gt;Uri Ronen&lt;/em&gt;` nen Twig no bien dich thanh html roi show ra ngoai. @sondoha
