### ISSUE TITLE
Carousel HTML

### ISSUE THREAD

**Issue by vietartisans** [vietartisans/templater#5]
We usually use carousel in our project and it takes a lot of time.

So we will need to put it here in our templater:

```php
echo $templater->carousel('layout', $data);
```

`$data` is an array, it contains all of your items (image, name, url).

Your carousel HTML should be placed in:

```
/wp-content/themes/{theme-name}/templates/carousel/layout.php
```

**Comment by theanhdo94** [comment]
@vietartisans Where to development on this?

**Comment by duyngha** [comment]
@vietartisans @theanhdo94 
As default layout, we should create them into `/templater/templates/carousel/layout.php`. So we don't need to copy everytime we create a new theme for project.

**Comment by vietartisans** [comment]
@theanhdo94 Fork this repo, deploy it on c9 and commit your changes

**Comment by vietartisans** [comment]
@duyngha Please tell me more, not quite understand what you mean.

**Comment by duyngha** [comment]
@vietartisans I meant we will place all our template files in `templater/templates/{type_list}/{layout_name}`. Dependence on requirements of specific project we should place them in `themes/{theme_name}/templates/{type_list}/{layout_name}` to override the default templates.

**Comment by vietartisans** [comment]
We will move this one to another repository
