### ISSUE TITLE
How can I debugging in template file

### ISSUE THREAD

**Issue by duyngha** [vietartisans/templater#6]
Hi mate,

I got this problem when I was using **templater** that I couldn't debugging the variable which passed to the template file. I went through the documentation but didn't get any luck. Regarding this problem, can I use object in template file?

**Comment by buiquangduc** [comment]
var_dump hen

**Comment by buiquangduc** [comment]
Use Blade template for debugging, because you can use php code in Blade template(var_dump, .....)
